"""
Weekly Sentiment Analytics Report
Generates a markdown summary of the past week's sentiment trends.
"""

import json
import os
from datetime import datetime, timedelta
from collections import Counter

DATA_DIR = os.path.join(os.path.dirname(os.path.dirname(__file__)), 'data')
MEMORY_FILE = os.path.join(DATA_DIR, 'memory.json')
REPORTS_DIR = os.path.join(DATA_DIR, 'reports')
os.makedirs(REPORTS_DIR, exist_ok=True)


def load_memory():
    try:
        with open(MEMORY_FILE, 'r') as f:
            return json.load(f)
    except (FileNotFoundError, json.JSONDecodeError):
        return {"entries": []}


def filter_week_entries(entries, week_start=None):
    if week_start is None:
        week_start = datetime.now().date() - timedelta(days=7)
    week_entries = []
    for entry in entries:
        try:
            dt = datetime.fromisoformat(entry['completed_at'].replace('Z', '+00:00'))
            if dt.date() >= week_start:
                week_entries.append(entry)
        except (KeyError, ValueError):
            continue
    return week_entries


def generate_report(entries, week_start):
    if not entries:
        return "# Weekly Sentiment Report

No data available for the selected period."
    
    total = len(entries)
    
    # Emotion distribution
    emotions = [e.get('emotion', 'unknown') for e in entries]
    emotion_counts = Counter(emotions)
    top_emotion = emotion_counts.most_common(1)[0] if emotion_counts else ('none', 0)
    
    # Category distribution
    categories = [e.get('category', 'unknown') for e in entries]
    category_counts = Counter(categories)
    top_category = category_counts.most_common(1)[0] if category_counts else ('none', 0)
    
    # Average intensity
    intensities = [e.get('intensity', 0) for e in entries if 'intensity' in e]
    avg_intensity = sum(intensities) / len(intensities) if intensities else 0
    
    # Date range in entries
    dates = [datetime.fromisoformat(e['completed_at'].replace('Z', '+00:00')).date() for e in entries if 'completed_at' in e]
    min_date = min(dates) if dates else week_start
    max_date = max(dates) if dates else datetime.now().date()
    
    # Build markdown
    report_date = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    week_label = f"{week_start.strftime('%Y-%m-%d')} to {datetime.now().date().strftime('%Y-%m-%d')}"
    
    md = f"""# Weekly Sentiment Analytics Report

**Generated:** {report_date}  
**Period:** {week_label}  
**Total Tasks Analyzed:** {total}

---

## 📊 Summary

- **Dominant Emotion:** {top_emotion[0]} ({top_emotion[1]} tasks, {top_emotion[1]/total*100:.1f}%)
- **Dominant Category:** {top_category[0]} ({top_category[1]} tasks, {top_category[1]/total*100:.1f}%)
- **Average Intensity:** {avg_intensity:.2f}
- **Date Range:** {min_date} - {max_date}

---

## 📈 Emotion Distribution

| Emotion | Count | Percentage |
|---------|-------|------------|
"""
    for emotion, count in emotion_counts.most_common():
        md += f"| {emotion} | {count} | {count/total*100:.1f}% |
"
    
    md += "
## 📂 Category Distribution

"
    md += "| Category | Count | Percentage |
|---------|-------|------------|
"
    for category, count in category_counts.most_common():
        md += f"| {category} | {count} | {count/total*100:.1f}% |
"
    
    md += "
---
*Report generated by OpenClaw Things Sentiment analytics.*
"
    return md


def main():
    memory = load_memory()
    entries = memory.get('entries', [])
    week_start = datetime.now().date() - timedelta(days=7)
    week_entries = filter_week_entries(entries, week_start)
    
    report = generate_report(week_entries, week_start)
    
    # Save with timestamp
    timestamp = datetime.now().strftime("%Y%m%d")
    report_file = os.path.join(REPORTS_DIR, f"weekly_report_{timestamp}.md")
    with open(report_file, 'w') as f:
        f.write(report)
    
    print(f"Weekly report generated: {report_file}")
    print(f"Tasks analyzed: {len(week_entries)}")
    return report_file


if __name__ == '__main__':
    main()
